sudo: true
language: node_js
node_js:
  - "10"

branches:
  only:
    - /.*/

install:
  - yarn install --production=false

script:
  - yarn lint
#  - yarn build
#  - yarn test
  - yarn doc
#  - bash scripts/publish.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      repo: capsulajs/capsula-hub
      all_branches: true
#      condition: ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^feature\/.*$

notifications:
  email:
    on_failure: always
